name: Deploy to thelocalghost.com

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to thelocalghost.com (root)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: \${{ secrets.FTP_HOST }}
          username: \${{ secrets.FTP_USERNAME }}
          password: \${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /localghost/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            polter/**
            README.md
